Import("env")

#env = env.Clone()

def source(file):
    return "#/src/engine/" + file

env["source_files"] += [
    source("app.cpp"),
    source("input.cpp"),
    source("render.cpp"),
    source("abstract_global_variables.cpp")
]


